name: Format files

on:
    pull_request:
        branches: [main]

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  # Make sure the actual branch is checked out when running on pull requests
                  ref: ${{ github.head_ref }}
                  # This is important to fetch the changes to the previous commit
                  fetch-depth: 0
                  
            - name: Install npm@v8
              run: npm i -g npm@8

            - name: Prettify code
              uses: creyD/prettier_action@v4.3
              with:
                  # This part is also where you can pass other options, for example:
                  prettier_options: --config .prettierrc
                  only_changed: True
